name: Build Windows ISO

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run UUP script
        run: |
          uup_download_windows.cmd

      - name: Upload ISO
        uses: actions/upload-artifact@v4
        with:
          name: WindowsISO
          path: "*.iso"

